apiVersion: batch/v1
kind: CronJob
metadata:
  name: rss
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbit
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: internal-harbor
          containers:
            - name: rss-cron
              image: registry.uniproject.jp/infra/unibot-rss-cron:1.0.0
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: unibot-env
              env:
                - name: TZ
                  value: Asia/Tokyo
