apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: unibot
spec:
  selector:
    matchLabels:
      app: unibot
  template:
    metadata:
      labels:
        app: unibot
    spec:
      containers:
        - name: unibot
          image: registry.uniproject.jp/infra/unibot:8.4.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: unibot-env
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: CONFIG_LOG_LEVEL
              value: "info"
            - name: CONFIG_LOG_FORMAT
              value: "json"
            - name: CONFIG_LOG_SQL
              value: "warn"
            - name: CONFIG_LOG_DISCORD_LEVEL
              value: "notice"
            - name: CONFIG_LOG_READY_CHANNEL_ID
              value: "1228574771856543835"
            - name: CONFIG_LOG_ERROR_CHANNEL_ID
              value: "1236638014919147570"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: internal-harbor
