apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - registry.yaml
  - env.yaml
  - pv-pvc.yaml
labels:
  - includeSelectors: true
    pairs:
      app: unibot
