---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: internal-harbor
spec:
  encryptedData:
    .dockerconfigjson: AgAHuN4ELETZt4j1b9l6u92VB648wGFZJZp5e4l+4/EWsN9REMVLH3/dEbpDlqvteSZL7FHVHgDWBpVp9um+PWQQwl4fd96u5VHrjIQsBfwN11cugJ0n1bqAm7T0gqzfuN0vHSGQEfaff+A0drUaZMmfuzLyJKKVL7bAJHIXOksYVP9Jg42gP3qCKIDd6FhBlO77sR3Or/mJQOta7TF1jf/YMeS+VgD/z+/BoI0JbGf+soTrDHDnJXIkq0K5mdS64XlOKL+4LiYc9W0LjLBmM+Z4RBAYwo92vL5dM55tPPL/5TjKzyL8lX2/W0ko85ZoAHIB6UbO+BOTQegDWQXTRaYkZCixM5TTBe4BoY8LVq+ZjrlBMW/WS26EE4xG3N04kYeQvOzh/Sq3UwtZP1IbnKdU3P7IqTr8zxMnaBUONONOXUpJhagW8O83LEgoi8Z8ANCjjpjWnavCRdjglaonee/jFLl61RzIE3aeYNroLr19Vm0TbVe7fdcfOEvI0gRsWq8WOwS0woX+gTL2jqAKQtvInNhx4bGa8DGJ9poNuOmJ10O7WYalIeoJa3+MRSfTb5RHyFLdCoM35HN5xZarOms92SFLtFJTohx4Ag5UyoFzXJcMqf6BQ3xR0Q3k5/EESVC1LV+8r1D6JyaLh0I1OXpXoeTLnrs4Ctj81zxX92f2KTmzDrlE7ShSnnmvuxYys4h7+YELU7kZuGNSHG+SYViSfZ0uImazD8O4u6Iy/w7RSqwLbwWl7f3ZOMTN2vgYzNremKT1LhbIFieeHVUNZ7a1bujPNriVijmrDuUFox2G94XL8GLf92lWgbvqTPqgWs5ZXC+hBqtWScbsZY+DC7utyJ+lVqa03pQfcb48dSsHXOLs4iDxrlwBOBOr6ugNYauyxQBscVwTf9IoSbVuZSk4wRUGaw5ODQovMHj4ml9EY+ovSQ+sgHk2ImqBifgpnQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: internal-harbor
    type: kubernetes.io/dockerconfigjson
