version: "3"
services:
  bot:
    container_name: unibot
    build: .
    restart: always
    env_file: .env
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=unibot
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres:
