// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameChannel = "channels"

// Channel mapped from table <channels>
type Channel struct {
	ID          int64          `gorm:"column:id;primaryKey;comment:Discord Channel ID (Snowflake ID)" json:"id"`           // Discord Channel ID (Snowflake ID)
	GuildID     int64          `gorm:"column:guild_id;not null;comment:Discord Guild ID (Snowflake ID)" json:"guild_id"`   // Discord Guild ID (Snowflake ID)
	IsSuspended bool           `gorm:"column:is_suspended;not null;comment:Is this channel suspended" json:"is_suspended"` // Is this channel suspended
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Channel's table name
func (*Channel) TableName() string {
	return TableNameChannel
}
