// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGuild = "guilds"

// Guild mapped from table <guilds>
type Guild struct {
	ID           int64          `gorm:"column:id;primaryKey;comment:Discord Guild ID (Snowflake ID)" json:"id"`                      // Discord Guild ID (Snowflake ID)
	IsAdmin      bool           `gorm:"column:is_admin;not null;comment:Which is it admin guild" json:"is_admin"`                    // Which is it admin guild
	IsSuspended  bool           `gorm:"column:is_suspended;not null;comment:Is this guild suspended" json:"is_suspended"`            // Is this guild suspended
	IsTtsEnabled bool           `gorm:"column:is_tts_enabled;not null;comment:Is available TTS in this guild" json:"is_tts_enabled"` // Is available TTS in this guild
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Guild's table name
func (*Guild) TableName() string {
	return TableNameGuild
}
