// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMember = "members"

// Member mapped from table <members>
type Member struct {
	UserID      int64          `gorm:"column:user_id;primaryKey;comment:Discord User ID (Snowflake ID)" json:"user_id"`    // Discord User ID (Snowflake ID)
	GuildID     int64          `gorm:"column:guild_id;primaryKey;comment:Discord Guild ID (Snowflake ID)" json:"guild_id"` // Discord Guild ID (Snowflake ID)
	IsSuspended bool           `gorm:"column:is_suspended;not null;comment:Is this user suspended" json:"is_suspended"`    // Is this user suspended
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
