// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePinSetting = "pin_settings"

// PinSetting mapped from table <pin_settings>
type PinSetting struct {
	ChannelID int64  `gorm:"column:channel_id;primaryKey" json:"channel_id"`
	UserID    int64  `gorm:"column:user_id;not null" json:"user_id"`
	Content   string `gorm:"column:content;not null" json:"content"`
	GuildID   int64  `gorm:"column:guild_id;not null" json:"guild_id"`
}

// TableName PinSetting's table name
func (*PinSetting) TableName() string {
	return TableNamePinSetting
}
