// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTtsUserPreference = "tts_user_preference"

// TtsUserPreference mapped from table <tts_user_preference>
type TtsUserPreference struct {
	UserID    int64 `gorm:"column:user_id;primaryKey" json:"user_id"`
	SpeakerID int32 `gorm:"column:speaker_id;not null" json:"speaker_id"`
	Speed     int32 `gorm:"column:speed;not null;default:100" json:"speed"`
}

// TableName TtsUserPreference's table name
func (*TtsUserPreference) TableName() string {
	return TableNameTtsUserPreference
}
