// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTtsDictionary = "tts_dictionary"

// TtsDictionary mapped from table <tts_dictionary>
type TtsDictionary struct {
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	GuildID   int64     `gorm:"column:guild_id;primaryKey" json:"guild_id"`
	Yomi      string    `gorm:"column:yomi;not null" json:"yomi"`
	Word      string    `gorm:"column:word;primaryKey" json:"word"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName TtsDictionary's table name
func (*TtsDictionary) TableName() string {
	return TableNameTtsDictionary
}
