apiVersion: apps/v1
kind: Deployment
metadata:
  name: unibot
spec:
  selector:
    matchLabels:
      app: unibot
  template:
    metadata:
      labels:
        app: unibot
    spec:
      containers:
      - name: unibot
        image: localhost:32000/unibot:3.2.0
        envFrom:
        - secretRef:
            name: unibot-env
        volumeMounts:
        - name: log
          mountPath: /app/log
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: logs
