apiVersion: v1
kind: PersistentVolume
metadata:
  name: unibot-logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/infra/unibot/logs
    server: 172.16.110.199
  claimRef:
    namespace: unibot
    name: logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  labels:
    app: unibot
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeName: unibot-logs