apiVersion: v1
kind: PersistentVolume
metadata:
  name: unibot-log
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/unibot/logs
    server: 172.16.110.199
  claimRef:
    namespace: unibot
    name: log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log
  labels:
    app: unibot
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeName: unibot-log