---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: unibot
spec:
  encryptedData:
    .dockerconfigjson: AgBzX8UUeTXYmMXlKpHZfNwM772wscoyy6Fq7sfg1P925844JkmqCcsmVthmqgNbqqhLEsHxVEfdK8XtVKRBwxBPjD4oJ+ceAxIxncAwLtVaIuuxbH81bV7fcReCCyXA3IzFVNcCcOTb4I7ob6Noi0ZP6oALkAIfdOxbLjOqIg7evW0KQeK9NR3uL3/59W8uU+T4gNvqVk6sgkn8G3FsLWuqWbDUiFn/e9mQVKlpoZGPMqmSAxM3TOdbvgHwg5Ah1iPw4dynUHnLsFBmzaZvVgysCUimDbqzC4HjJy76S48u/Gb/KMBakrrSAsC8PkK5xmTK/cO+wKeNCR0Czs6gA3VGzf+EKi6V5uPLlwyjh7bLUpQxQA4wqMo6VSXw7A2xOKvbIZ1dMJw5A5hLxonF2khGIldjdRZFRZB75pmNLVk61d3hD709ZLuH0YN4YuJbWoTUNF7yPP92zxECIj057c/+ZUFerSHN4PGRCTRlBgUs7kv5so3ncZqrotqkhG4LE4SpXoSAZr1mHF2mbVGKpi4iJ2rhuiauzMBMP8cBrye1E7umvb3sBDACvOlXiEaVJUZQTE/ILEHgfhis2XBLLLGFoen3cy1dyCWUowCB9/jR4rMswD6dtuoYHU0skdKDk7chTGhT8ph+ckXAlW2QIWDny7j7TT1KDaHDuJyjfbIbBBP4lqpS8uaHeNfaIsKtOmvXHfh3N1qs4wOfIk5y94oJ7K+vRgi4OShvcLY9mqxG5ykvH7g/0I4jGWtCIhutFZcnLnpNVr/na/AjWdiwiIDIMYyvEn+BrPx4wblHqiZltQFsgcXrV+2NtyuTwKd1TtY8NC+76jLh7EfWE2OfCfYXZbl8Rs3TViQiqNsVRITPT4V1+qLsZKjw5gwSIrawmw4xeFtL8M5Hja5x/cCj59dmZXfMUB670wiBhIejkyNfRi1WgkmvVF9MJk+O94p2yG9AmSzQN2RTRw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: unibot
    type: kubernetes.io/dockerconfigjson
