apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: unibot
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "unibot"
      images:
        - alias: "unibot"
          imageName: "registry.uniproject.jp/unibot/unibot"
          commonUpdateSettings:
            updateStrategy: "semver"
