// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	Channel             *channel
	Guild               *guild
	Member              *member
	PinSetting          *pinSetting
	RemindSetting       *remindSetting
	RssSetting          *rssSetting
	SystemPreference    *systemPreference
	TtsConnection       *ttsConnection
	TtsDictionary       *ttsDictionary
	TtsMemberPreference *ttsMemberPreference
	TtsUserPreference   *ttsUserPreference
	User                *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Channel = &Q.Channel
	Guild = &Q.Guild
	Member = &Q.Member
	PinSetting = &Q.PinSetting
	RemindSetting = &Q.RemindSetting
	RssSetting = &Q.RssSetting
	SystemPreference = &Q.SystemPreference
	TtsConnection = &Q.TtsConnection
	TtsDictionary = &Q.TtsDictionary
	TtsMemberPreference = &Q.TtsMemberPreference
	TtsUserPreference = &Q.TtsUserPreference
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		Channel:             newChannel(db, opts...),
		Guild:               newGuild(db, opts...),
		Member:              newMember(db, opts...),
		PinSetting:          newPinSetting(db, opts...),
		RemindSetting:       newRemindSetting(db, opts...),
		RssSetting:          newRssSetting(db, opts...),
		SystemPreference:    newSystemPreference(db, opts...),
		TtsConnection:       newTtsConnection(db, opts...),
		TtsDictionary:       newTtsDictionary(db, opts...),
		TtsMemberPreference: newTtsMemberPreference(db, opts...),
		TtsUserPreference:   newTtsUserPreference(db, opts...),
		User:                newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Channel             channel
	Guild               guild
	Member              member
	PinSetting          pinSetting
	RemindSetting       remindSetting
	RssSetting          rssSetting
	SystemPreference    systemPreference
	TtsConnection       ttsConnection
	TtsDictionary       ttsDictionary
	TtsMemberPreference ttsMemberPreference
	TtsUserPreference   ttsUserPreference
	User                user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Channel:             q.Channel.clone(db),
		Guild:               q.Guild.clone(db),
		Member:              q.Member.clone(db),
		PinSetting:          q.PinSetting.clone(db),
		RemindSetting:       q.RemindSetting.clone(db),
		RssSetting:          q.RssSetting.clone(db),
		SystemPreference:    q.SystemPreference.clone(db),
		TtsConnection:       q.TtsConnection.clone(db),
		TtsDictionary:       q.TtsDictionary.clone(db),
		TtsMemberPreference: q.TtsMemberPreference.clone(db),
		TtsUserPreference:   q.TtsUserPreference.clone(db),
		User:                q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		Channel:             q.Channel.replaceDB(db),
		Guild:               q.Guild.replaceDB(db),
		Member:              q.Member.replaceDB(db),
		PinSetting:          q.PinSetting.replaceDB(db),
		RemindSetting:       q.RemindSetting.replaceDB(db),
		RssSetting:          q.RssSetting.replaceDB(db),
		SystemPreference:    q.SystemPreference.replaceDB(db),
		TtsConnection:       q.TtsConnection.replaceDB(db),
		TtsDictionary:       q.TtsDictionary.replaceDB(db),
		TtsMemberPreference: q.TtsMemberPreference.replaceDB(db),
		TtsUserPreference:   q.TtsUserPreference.replaceDB(db),
		User:                q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Channel             IChannelDo
	Guild               IGuildDo
	Member              IMemberDo
	PinSetting          IPinSettingDo
	RemindSetting       IRemindSettingDo
	RssSetting          IRssSettingDo
	SystemPreference    ISystemPreferenceDo
	TtsConnection       ITtsConnectionDo
	TtsDictionary       ITtsDictionaryDo
	TtsMemberPreference ITtsMemberPreferenceDo
	TtsUserPreference   ITtsUserPreferenceDo
	User                IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Channel:             q.Channel.WithContext(ctx),
		Guild:               q.Guild.WithContext(ctx),
		Member:              q.Member.WithContext(ctx),
		PinSetting:          q.PinSetting.WithContext(ctx),
		RemindSetting:       q.RemindSetting.WithContext(ctx),
		RssSetting:          q.RssSetting.WithContext(ctx),
		SystemPreference:    q.SystemPreference.WithContext(ctx),
		TtsConnection:       q.TtsConnection.WithContext(ctx),
		TtsDictionary:       q.TtsDictionary.WithContext(ctx),
		TtsMemberPreference: q.TtsMemberPreference.WithContext(ctx),
		TtsUserPreference:   q.TtsUserPreference.WithContext(ctx),
		User:                q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
