// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newGuild(db *gorm.DB, opts ...gen.DOOption) guild {
	_guild := guild{}

	_guild.guildDo.UseDB(db, opts...)
	_guild.guildDo.UseModel(&model.Guild{})

	tableName := _guild.guildDo.TableName()
	_guild.ALL = field.NewAsterisk(tableName)
	_guild.ID = field.NewInt64(tableName, "id")
	_guild.IsAdmin = field.NewBool(tableName, "is_admin")
	_guild.IsSuspended = field.NewBool(tableName, "is_suspended")
	_guild.IsTtsEnabled = field.NewBool(tableName, "is_tts_enabled")
	_guild.CreatedAt = field.NewTime(tableName, "created_at")
	_guild.UpdatedAt = field.NewTime(tableName, "updated_at")
	_guild.DeletedAt = field.NewField(tableName, "deleted_at")

	_guild.fillFieldMap()

	return _guild
}

type guild struct {
	guildDo

	ALL          field.Asterisk
	ID           field.Int64 // Discord Guild ID (Snowflake ID)
	IsAdmin      field.Bool  // Which is it admin guild
	IsSuspended  field.Bool  // Is this guild suspended
	IsTtsEnabled field.Bool  // Is available TTS in this guild
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field

	fieldMap map[string]field.Expr
}

func (g guild) Table(newTableName string) *guild {
	g.guildDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g guild) As(alias string) *guild {
	g.guildDo.DO = *(g.guildDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *guild) updateTableName(table string) *guild {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.IsAdmin = field.NewBool(table, "is_admin")
	g.IsSuspended = field.NewBool(table, "is_suspended")
	g.IsTtsEnabled = field.NewBool(table, "is_tts_enabled")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *guild) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *guild) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 7)
	g.fieldMap["id"] = g.ID
	g.fieldMap["is_admin"] = g.IsAdmin
	g.fieldMap["is_suspended"] = g.IsSuspended
	g.fieldMap["is_tts_enabled"] = g.IsTtsEnabled
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g guild) clone(db *gorm.DB) guild {
	g.guildDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g guild) replaceDB(db *gorm.DB) guild {
	g.guildDo.ReplaceDB(db)
	return g
}

type guildDo struct{ gen.DO }

type IGuildDo interface {
	gen.SubQuery
	Debug() IGuildDo
	WithContext(ctx context.Context) IGuildDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGuildDo
	WriteDB() IGuildDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGuildDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGuildDo
	Not(conds ...gen.Condition) IGuildDo
	Or(conds ...gen.Condition) IGuildDo
	Select(conds ...field.Expr) IGuildDo
	Where(conds ...gen.Condition) IGuildDo
	Order(conds ...field.Expr) IGuildDo
	Distinct(cols ...field.Expr) IGuildDo
	Omit(cols ...field.Expr) IGuildDo
	Join(table schema.Tabler, on ...field.Expr) IGuildDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGuildDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGuildDo
	Group(cols ...field.Expr) IGuildDo
	Having(conds ...gen.Condition) IGuildDo
	Limit(limit int) IGuildDo
	Offset(offset int) IGuildDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGuildDo
	Unscoped() IGuildDo
	Create(values ...*model.Guild) error
	CreateInBatches(values []*model.Guild, batchSize int) error
	Save(values ...*model.Guild) error
	First() (*model.Guild, error)
	Take() (*model.Guild, error)
	Last() (*model.Guild, error)
	Find() ([]*model.Guild, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Guild, err error)
	FindInBatches(result *[]*model.Guild, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Guild) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGuildDo
	Assign(attrs ...field.AssignExpr) IGuildDo
	Joins(fields ...field.RelationField) IGuildDo
	Preload(fields ...field.RelationField) IGuildDo
	FirstOrInit() (*model.Guild, error)
	FirstOrCreate() (*model.Guild, error)
	FindByPage(offset int, limit int) (result []*model.Guild, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGuildDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g guildDo) Debug() IGuildDo {
	return g.withDO(g.DO.Debug())
}

func (g guildDo) WithContext(ctx context.Context) IGuildDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g guildDo) ReadDB() IGuildDo {
	return g.Clauses(dbresolver.Read)
}

func (g guildDo) WriteDB() IGuildDo {
	return g.Clauses(dbresolver.Write)
}

func (g guildDo) Session(config *gorm.Session) IGuildDo {
	return g.withDO(g.DO.Session(config))
}

func (g guildDo) Clauses(conds ...clause.Expression) IGuildDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g guildDo) Returning(value interface{}, columns ...string) IGuildDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g guildDo) Not(conds ...gen.Condition) IGuildDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g guildDo) Or(conds ...gen.Condition) IGuildDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g guildDo) Select(conds ...field.Expr) IGuildDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g guildDo) Where(conds ...gen.Condition) IGuildDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g guildDo) Order(conds ...field.Expr) IGuildDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g guildDo) Distinct(cols ...field.Expr) IGuildDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g guildDo) Omit(cols ...field.Expr) IGuildDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g guildDo) Join(table schema.Tabler, on ...field.Expr) IGuildDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g guildDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGuildDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g guildDo) RightJoin(table schema.Tabler, on ...field.Expr) IGuildDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g guildDo) Group(cols ...field.Expr) IGuildDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g guildDo) Having(conds ...gen.Condition) IGuildDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g guildDo) Limit(limit int) IGuildDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g guildDo) Offset(offset int) IGuildDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g guildDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGuildDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g guildDo) Unscoped() IGuildDo {
	return g.withDO(g.DO.Unscoped())
}

func (g guildDo) Create(values ...*model.Guild) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g guildDo) CreateInBatches(values []*model.Guild, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g guildDo) Save(values ...*model.Guild) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g guildDo) First() (*model.Guild, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Guild), nil
	}
}

func (g guildDo) Take() (*model.Guild, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Guild), nil
	}
}

func (g guildDo) Last() (*model.Guild, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Guild), nil
	}
}

func (g guildDo) Find() ([]*model.Guild, error) {
	result, err := g.DO.Find()
	return result.([]*model.Guild), err
}

func (g guildDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Guild, err error) {
	buf := make([]*model.Guild, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g guildDo) FindInBatches(result *[]*model.Guild, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g guildDo) Attrs(attrs ...field.AssignExpr) IGuildDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g guildDo) Assign(attrs ...field.AssignExpr) IGuildDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g guildDo) Joins(fields ...field.RelationField) IGuildDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g guildDo) Preload(fields ...field.RelationField) IGuildDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g guildDo) FirstOrInit() (*model.Guild, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Guild), nil
	}
}

func (g guildDo) FirstOrCreate() (*model.Guild, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Guild), nil
	}
}

func (g guildDo) FindByPage(offset int, limit int) (result []*model.Guild, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g guildDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g guildDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g guildDo) Delete(models ...*model.Guild) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *guildDo) withDO(do gen.Dao) *guildDo {
	g.DO = *do.(*gen.DO)
	return g
}
