// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newPinSetting(db *gorm.DB, opts ...gen.DOOption) pinSetting {
	_pinSetting := pinSetting{}

	_pinSetting.pinSettingDo.UseDB(db, opts...)
	_pinSetting.pinSettingDo.UseModel(&model.PinSetting{})

	tableName := _pinSetting.pinSettingDo.TableName()
	_pinSetting.ALL = field.NewAsterisk(tableName)
	_pinSetting.ChannelID = field.NewInt64(tableName, "channel_id")
	_pinSetting.UserID = field.NewInt64(tableName, "user_id")
	_pinSetting.GuildID = field.NewInt64(tableName, "guild_id")
	_pinSetting.Content = field.NewString(tableName, "content")

	_pinSetting.fillFieldMap()

	return _pinSetting
}

type pinSetting struct {
	pinSettingDo

	ALL       field.Asterisk
	ChannelID field.Int64
	UserID    field.Int64
	GuildID   field.Int64
	Content   field.String

	fieldMap map[string]field.Expr
}

func (p pinSetting) Table(newTableName string) *pinSetting {
	p.pinSettingDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pinSetting) As(alias string) *pinSetting {
	p.pinSettingDo.DO = *(p.pinSettingDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pinSetting) updateTableName(table string) *pinSetting {
	p.ALL = field.NewAsterisk(table)
	p.ChannelID = field.NewInt64(table, "channel_id")
	p.UserID = field.NewInt64(table, "user_id")
	p.GuildID = field.NewInt64(table, "guild_id")
	p.Content = field.NewString(table, "content")

	p.fillFieldMap()

	return p
}

func (p *pinSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pinSetting) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["channel_id"] = p.ChannelID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["guild_id"] = p.GuildID
	p.fieldMap["content"] = p.Content
}

func (p pinSetting) clone(db *gorm.DB) pinSetting {
	p.pinSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pinSetting) replaceDB(db *gorm.DB) pinSetting {
	p.pinSettingDo.ReplaceDB(db)
	return p
}

type pinSettingDo struct{ gen.DO }

type IPinSettingDo interface {
	gen.SubQuery
	Debug() IPinSettingDo
	WithContext(ctx context.Context) IPinSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPinSettingDo
	WriteDB() IPinSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPinSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPinSettingDo
	Not(conds ...gen.Condition) IPinSettingDo
	Or(conds ...gen.Condition) IPinSettingDo
	Select(conds ...field.Expr) IPinSettingDo
	Where(conds ...gen.Condition) IPinSettingDo
	Order(conds ...field.Expr) IPinSettingDo
	Distinct(cols ...field.Expr) IPinSettingDo
	Omit(cols ...field.Expr) IPinSettingDo
	Join(table schema.Tabler, on ...field.Expr) IPinSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPinSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPinSettingDo
	Group(cols ...field.Expr) IPinSettingDo
	Having(conds ...gen.Condition) IPinSettingDo
	Limit(limit int) IPinSettingDo
	Offset(offset int) IPinSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPinSettingDo
	Unscoped() IPinSettingDo
	Create(values ...*model.PinSetting) error
	CreateInBatches(values []*model.PinSetting, batchSize int) error
	Save(values ...*model.PinSetting) error
	First() (*model.PinSetting, error)
	Take() (*model.PinSetting, error)
	Last() (*model.PinSetting, error)
	Find() ([]*model.PinSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PinSetting, err error)
	FindInBatches(result *[]*model.PinSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PinSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPinSettingDo
	Assign(attrs ...field.AssignExpr) IPinSettingDo
	Joins(fields ...field.RelationField) IPinSettingDo
	Preload(fields ...field.RelationField) IPinSettingDo
	FirstOrInit() (*model.PinSetting, error)
	FirstOrCreate() (*model.PinSetting, error)
	FindByPage(offset int, limit int) (result []*model.PinSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPinSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pinSettingDo) Debug() IPinSettingDo {
	return p.withDO(p.DO.Debug())
}

func (p pinSettingDo) WithContext(ctx context.Context) IPinSettingDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pinSettingDo) ReadDB() IPinSettingDo {
	return p.Clauses(dbresolver.Read)
}

func (p pinSettingDo) WriteDB() IPinSettingDo {
	return p.Clauses(dbresolver.Write)
}

func (p pinSettingDo) Session(config *gorm.Session) IPinSettingDo {
	return p.withDO(p.DO.Session(config))
}

func (p pinSettingDo) Clauses(conds ...clause.Expression) IPinSettingDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pinSettingDo) Returning(value interface{}, columns ...string) IPinSettingDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pinSettingDo) Not(conds ...gen.Condition) IPinSettingDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pinSettingDo) Or(conds ...gen.Condition) IPinSettingDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pinSettingDo) Select(conds ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pinSettingDo) Where(conds ...gen.Condition) IPinSettingDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pinSettingDo) Order(conds ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pinSettingDo) Distinct(cols ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pinSettingDo) Omit(cols ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pinSettingDo) Join(table schema.Tabler, on ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pinSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pinSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pinSettingDo) Group(cols ...field.Expr) IPinSettingDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pinSettingDo) Having(conds ...gen.Condition) IPinSettingDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pinSettingDo) Limit(limit int) IPinSettingDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pinSettingDo) Offset(offset int) IPinSettingDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pinSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPinSettingDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pinSettingDo) Unscoped() IPinSettingDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pinSettingDo) Create(values ...*model.PinSetting) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pinSettingDo) CreateInBatches(values []*model.PinSetting, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pinSettingDo) Save(values ...*model.PinSetting) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pinSettingDo) First() (*model.PinSetting, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PinSetting), nil
	}
}

func (p pinSettingDo) Take() (*model.PinSetting, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PinSetting), nil
	}
}

func (p pinSettingDo) Last() (*model.PinSetting, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PinSetting), nil
	}
}

func (p pinSettingDo) Find() ([]*model.PinSetting, error) {
	result, err := p.DO.Find()
	return result.([]*model.PinSetting), err
}

func (p pinSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PinSetting, err error) {
	buf := make([]*model.PinSetting, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pinSettingDo) FindInBatches(result *[]*model.PinSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pinSettingDo) Attrs(attrs ...field.AssignExpr) IPinSettingDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pinSettingDo) Assign(attrs ...field.AssignExpr) IPinSettingDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pinSettingDo) Joins(fields ...field.RelationField) IPinSettingDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pinSettingDo) Preload(fields ...field.RelationField) IPinSettingDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pinSettingDo) FirstOrInit() (*model.PinSetting, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PinSetting), nil
	}
}

func (p pinSettingDo) FirstOrCreate() (*model.PinSetting, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PinSetting), nil
	}
}

func (p pinSettingDo) FindByPage(offset int, limit int) (result []*model.PinSetting, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pinSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pinSettingDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pinSettingDo) Delete(models ...*model.PinSetting) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pinSettingDo) withDO(do gen.Dao) *pinSettingDo {
	p.DO = *do.(*gen.DO)
	return p
}
