// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newRemindSetting(db *gorm.DB, opts ...gen.DOOption) remindSetting {
	_remindSetting := remindSetting{}

	_remindSetting.remindSettingDo.UseDB(db, opts...)
	_remindSetting.remindSettingDo.UseModel(&model.RemindSetting{})

	tableName := _remindSetting.remindSettingDo.TableName()
	_remindSetting.ALL = field.NewAsterisk(tableName)
	_remindSetting.ID = field.NewString(tableName, "id")
	_remindSetting.UserID = field.NewInt64(tableName, "user_id")
	_remindSetting.ChannelID = field.NewInt64(tableName, "channel_id")
	_remindSetting.Content = field.NewString(tableName, "content")
	_remindSetting.LastRun = field.NewTime(tableName, "last_run")
	_remindSetting.NextRun = field.NewTime(tableName, "next_run")
	_remindSetting.CronExpr = field.NewString(tableName, "cron_expr")
	_remindSetting.CreatedAt = field.NewTime(tableName, "created_at")

	_remindSetting.fillFieldMap()

	return _remindSetting
}

type remindSetting struct {
	remindSettingDo

	ALL       field.Asterisk
	ID        field.String
	UserID    field.Int64
	ChannelID field.Int64
	Content   field.String
	LastRun   field.Time
	NextRun   field.Time
	CronExpr  field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r remindSetting) Table(newTableName string) *remindSetting {
	r.remindSettingDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r remindSetting) As(alias string) *remindSetting {
	r.remindSettingDo.DO = *(r.remindSettingDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *remindSetting) updateTableName(table string) *remindSetting {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.UserID = field.NewInt64(table, "user_id")
	r.ChannelID = field.NewInt64(table, "channel_id")
	r.Content = field.NewString(table, "content")
	r.LastRun = field.NewTime(table, "last_run")
	r.NextRun = field.NewTime(table, "next_run")
	r.CronExpr = field.NewString(table, "cron_expr")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *remindSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *remindSetting) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["channel_id"] = r.ChannelID
	r.fieldMap["content"] = r.Content
	r.fieldMap["last_run"] = r.LastRun
	r.fieldMap["next_run"] = r.NextRun
	r.fieldMap["cron_expr"] = r.CronExpr
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r remindSetting) clone(db *gorm.DB) remindSetting {
	r.remindSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r remindSetting) replaceDB(db *gorm.DB) remindSetting {
	r.remindSettingDo.ReplaceDB(db)
	return r
}

type remindSettingDo struct{ gen.DO }

type IRemindSettingDo interface {
	gen.SubQuery
	Debug() IRemindSettingDo
	WithContext(ctx context.Context) IRemindSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRemindSettingDo
	WriteDB() IRemindSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRemindSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRemindSettingDo
	Not(conds ...gen.Condition) IRemindSettingDo
	Or(conds ...gen.Condition) IRemindSettingDo
	Select(conds ...field.Expr) IRemindSettingDo
	Where(conds ...gen.Condition) IRemindSettingDo
	Order(conds ...field.Expr) IRemindSettingDo
	Distinct(cols ...field.Expr) IRemindSettingDo
	Omit(cols ...field.Expr) IRemindSettingDo
	Join(table schema.Tabler, on ...field.Expr) IRemindSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRemindSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRemindSettingDo
	Group(cols ...field.Expr) IRemindSettingDo
	Having(conds ...gen.Condition) IRemindSettingDo
	Limit(limit int) IRemindSettingDo
	Offset(offset int) IRemindSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRemindSettingDo
	Unscoped() IRemindSettingDo
	Create(values ...*model.RemindSetting) error
	CreateInBatches(values []*model.RemindSetting, batchSize int) error
	Save(values ...*model.RemindSetting) error
	First() (*model.RemindSetting, error)
	Take() (*model.RemindSetting, error)
	Last() (*model.RemindSetting, error)
	Find() ([]*model.RemindSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RemindSetting, err error)
	FindInBatches(result *[]*model.RemindSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RemindSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRemindSettingDo
	Assign(attrs ...field.AssignExpr) IRemindSettingDo
	Joins(fields ...field.RelationField) IRemindSettingDo
	Preload(fields ...field.RelationField) IRemindSettingDo
	FirstOrInit() (*model.RemindSetting, error)
	FirstOrCreate() (*model.RemindSetting, error)
	FindByPage(offset int, limit int) (result []*model.RemindSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRemindSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r remindSettingDo) Debug() IRemindSettingDo {
	return r.withDO(r.DO.Debug())
}

func (r remindSettingDo) WithContext(ctx context.Context) IRemindSettingDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r remindSettingDo) ReadDB() IRemindSettingDo {
	return r.Clauses(dbresolver.Read)
}

func (r remindSettingDo) WriteDB() IRemindSettingDo {
	return r.Clauses(dbresolver.Write)
}

func (r remindSettingDo) Session(config *gorm.Session) IRemindSettingDo {
	return r.withDO(r.DO.Session(config))
}

func (r remindSettingDo) Clauses(conds ...clause.Expression) IRemindSettingDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r remindSettingDo) Returning(value interface{}, columns ...string) IRemindSettingDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r remindSettingDo) Not(conds ...gen.Condition) IRemindSettingDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r remindSettingDo) Or(conds ...gen.Condition) IRemindSettingDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r remindSettingDo) Select(conds ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r remindSettingDo) Where(conds ...gen.Condition) IRemindSettingDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r remindSettingDo) Order(conds ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r remindSettingDo) Distinct(cols ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r remindSettingDo) Omit(cols ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r remindSettingDo) Join(table schema.Tabler, on ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r remindSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r remindSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r remindSettingDo) Group(cols ...field.Expr) IRemindSettingDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r remindSettingDo) Having(conds ...gen.Condition) IRemindSettingDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r remindSettingDo) Limit(limit int) IRemindSettingDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r remindSettingDo) Offset(offset int) IRemindSettingDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r remindSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRemindSettingDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r remindSettingDo) Unscoped() IRemindSettingDo {
	return r.withDO(r.DO.Unscoped())
}

func (r remindSettingDo) Create(values ...*model.RemindSetting) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r remindSettingDo) CreateInBatches(values []*model.RemindSetting, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r remindSettingDo) Save(values ...*model.RemindSetting) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r remindSettingDo) First() (*model.RemindSetting, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemindSetting), nil
	}
}

func (r remindSettingDo) Take() (*model.RemindSetting, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemindSetting), nil
	}
}

func (r remindSettingDo) Last() (*model.RemindSetting, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemindSetting), nil
	}
}

func (r remindSettingDo) Find() ([]*model.RemindSetting, error) {
	result, err := r.DO.Find()
	return result.([]*model.RemindSetting), err
}

func (r remindSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RemindSetting, err error) {
	buf := make([]*model.RemindSetting, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r remindSettingDo) FindInBatches(result *[]*model.RemindSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r remindSettingDo) Attrs(attrs ...field.AssignExpr) IRemindSettingDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r remindSettingDo) Assign(attrs ...field.AssignExpr) IRemindSettingDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r remindSettingDo) Joins(fields ...field.RelationField) IRemindSettingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r remindSettingDo) Preload(fields ...field.RelationField) IRemindSettingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r remindSettingDo) FirstOrInit() (*model.RemindSetting, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemindSetting), nil
	}
}

func (r remindSettingDo) FirstOrCreate() (*model.RemindSetting, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RemindSetting), nil
	}
}

func (r remindSettingDo) FindByPage(offset int, limit int) (result []*model.RemindSetting, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r remindSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r remindSettingDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r remindSettingDo) Delete(models ...*model.RemindSetting) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *remindSettingDo) withDO(do gen.Dao) *remindSettingDo {
	r.DO = *do.(*gen.DO)
	return r
}
