// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newRssSetting(db *gorm.DB, opts ...gen.DOOption) rssSetting {
	_rssSetting := rssSetting{}

	_rssSetting.rssSettingDo.UseDB(db, opts...)
	_rssSetting.rssSettingDo.UseModel(&model.RssSetting{})

	tableName := _rssSetting.rssSettingDo.TableName()
	_rssSetting.ALL = field.NewAsterisk(tableName)
	_rssSetting.ID = field.NewString(tableName, "id")
	_rssSetting.UserID = field.NewInt64(tableName, "user_id")
	_rssSetting.ChannelID = field.NewInt64(tableName, "channel_id")
	_rssSetting.URL = field.NewString(tableName, "url")
	_rssSetting.LastRun = field.NewTime(tableName, "last_run")
	_rssSetting.CreatedAt = field.NewTime(tableName, "created_at")

	_rssSetting.fillFieldMap()

	return _rssSetting
}

type rssSetting struct {
	rssSettingDo

	ALL       field.Asterisk
	ID        field.String
	UserID    field.Int64
	ChannelID field.Int64
	URL       field.String
	LastRun   field.Time
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r rssSetting) Table(newTableName string) *rssSetting {
	r.rssSettingDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rssSetting) As(alias string) *rssSetting {
	r.rssSettingDo.DO = *(r.rssSettingDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rssSetting) updateTableName(table string) *rssSetting {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.UserID = field.NewInt64(table, "user_id")
	r.ChannelID = field.NewInt64(table, "channel_id")
	r.URL = field.NewString(table, "url")
	r.LastRun = field.NewTime(table, "last_run")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *rssSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rssSetting) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["channel_id"] = r.ChannelID
	r.fieldMap["url"] = r.URL
	r.fieldMap["last_run"] = r.LastRun
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r rssSetting) clone(db *gorm.DB) rssSetting {
	r.rssSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rssSetting) replaceDB(db *gorm.DB) rssSetting {
	r.rssSettingDo.ReplaceDB(db)
	return r
}

type rssSettingDo struct{ gen.DO }

type IRssSettingDo interface {
	gen.SubQuery
	Debug() IRssSettingDo
	WithContext(ctx context.Context) IRssSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRssSettingDo
	WriteDB() IRssSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRssSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRssSettingDo
	Not(conds ...gen.Condition) IRssSettingDo
	Or(conds ...gen.Condition) IRssSettingDo
	Select(conds ...field.Expr) IRssSettingDo
	Where(conds ...gen.Condition) IRssSettingDo
	Order(conds ...field.Expr) IRssSettingDo
	Distinct(cols ...field.Expr) IRssSettingDo
	Omit(cols ...field.Expr) IRssSettingDo
	Join(table schema.Tabler, on ...field.Expr) IRssSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRssSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRssSettingDo
	Group(cols ...field.Expr) IRssSettingDo
	Having(conds ...gen.Condition) IRssSettingDo
	Limit(limit int) IRssSettingDo
	Offset(offset int) IRssSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRssSettingDo
	Unscoped() IRssSettingDo
	Create(values ...*model.RssSetting) error
	CreateInBatches(values []*model.RssSetting, batchSize int) error
	Save(values ...*model.RssSetting) error
	First() (*model.RssSetting, error)
	Take() (*model.RssSetting, error)
	Last() (*model.RssSetting, error)
	Find() ([]*model.RssSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RssSetting, err error)
	FindInBatches(result *[]*model.RssSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RssSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRssSettingDo
	Assign(attrs ...field.AssignExpr) IRssSettingDo
	Joins(fields ...field.RelationField) IRssSettingDo
	Preload(fields ...field.RelationField) IRssSettingDo
	FirstOrInit() (*model.RssSetting, error)
	FirstOrCreate() (*model.RssSetting, error)
	FindByPage(offset int, limit int) (result []*model.RssSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRssSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rssSettingDo) Debug() IRssSettingDo {
	return r.withDO(r.DO.Debug())
}

func (r rssSettingDo) WithContext(ctx context.Context) IRssSettingDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rssSettingDo) ReadDB() IRssSettingDo {
	return r.Clauses(dbresolver.Read)
}

func (r rssSettingDo) WriteDB() IRssSettingDo {
	return r.Clauses(dbresolver.Write)
}

func (r rssSettingDo) Session(config *gorm.Session) IRssSettingDo {
	return r.withDO(r.DO.Session(config))
}

func (r rssSettingDo) Clauses(conds ...clause.Expression) IRssSettingDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rssSettingDo) Returning(value interface{}, columns ...string) IRssSettingDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rssSettingDo) Not(conds ...gen.Condition) IRssSettingDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rssSettingDo) Or(conds ...gen.Condition) IRssSettingDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rssSettingDo) Select(conds ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rssSettingDo) Where(conds ...gen.Condition) IRssSettingDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rssSettingDo) Order(conds ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rssSettingDo) Distinct(cols ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rssSettingDo) Omit(cols ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rssSettingDo) Join(table schema.Tabler, on ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rssSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rssSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rssSettingDo) Group(cols ...field.Expr) IRssSettingDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rssSettingDo) Having(conds ...gen.Condition) IRssSettingDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rssSettingDo) Limit(limit int) IRssSettingDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rssSettingDo) Offset(offset int) IRssSettingDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rssSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRssSettingDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rssSettingDo) Unscoped() IRssSettingDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rssSettingDo) Create(values ...*model.RssSetting) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rssSettingDo) CreateInBatches(values []*model.RssSetting, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rssSettingDo) Save(values ...*model.RssSetting) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rssSettingDo) First() (*model.RssSetting, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RssSetting), nil
	}
}

func (r rssSettingDo) Take() (*model.RssSetting, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RssSetting), nil
	}
}

func (r rssSettingDo) Last() (*model.RssSetting, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RssSetting), nil
	}
}

func (r rssSettingDo) Find() ([]*model.RssSetting, error) {
	result, err := r.DO.Find()
	return result.([]*model.RssSetting), err
}

func (r rssSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RssSetting, err error) {
	buf := make([]*model.RssSetting, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rssSettingDo) FindInBatches(result *[]*model.RssSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rssSettingDo) Attrs(attrs ...field.AssignExpr) IRssSettingDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rssSettingDo) Assign(attrs ...field.AssignExpr) IRssSettingDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rssSettingDo) Joins(fields ...field.RelationField) IRssSettingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rssSettingDo) Preload(fields ...field.RelationField) IRssSettingDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rssSettingDo) FirstOrInit() (*model.RssSetting, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RssSetting), nil
	}
}

func (r rssSettingDo) FirstOrCreate() (*model.RssSetting, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RssSetting), nil
	}
}

func (r rssSettingDo) FindByPage(offset int, limit int) (result []*model.RssSetting, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rssSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rssSettingDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rssSettingDo) Delete(models ...*model.RssSetting) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rssSettingDo) withDO(do gen.Dao) *rssSettingDo {
	r.DO = *do.(*gen.DO)
	return r
}
