// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newSystemPreference(db *gorm.DB, opts ...gen.DOOption) systemPreference {
	_systemPreference := systemPreference{}

	_systemPreference.systemPreferenceDo.UseDB(db, opts...)
	_systemPreference.systemPreferenceDo.UseModel(&model.SystemPreference{})

	tableName := _systemPreference.systemPreferenceDo.TableName()
	_systemPreference.ALL = field.NewAsterisk(tableName)
	_systemPreference.ID = field.NewString(tableName, "id")
	_systemPreference.StatusType = field.NewString(tableName, "status_type")
	_systemPreference.ActivityType = field.NewString(tableName, "activity_type")
	_systemPreference.ActivitySummary = field.NewString(tableName, "activity_summary")

	_systemPreference.fillFieldMap()

	return _systemPreference
}

type systemPreference struct {
	systemPreferenceDo

	ALL             field.Asterisk
	ID              field.String
	StatusType      field.String
	ActivityType    field.String
	ActivitySummary field.String

	fieldMap map[string]field.Expr
}

func (s systemPreference) Table(newTableName string) *systemPreference {
	s.systemPreferenceDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemPreference) As(alias string) *systemPreference {
	s.systemPreferenceDo.DO = *(s.systemPreferenceDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemPreference) updateTableName(table string) *systemPreference {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.StatusType = field.NewString(table, "status_type")
	s.ActivityType = field.NewString(table, "activity_type")
	s.ActivitySummary = field.NewString(table, "activity_summary")

	s.fillFieldMap()

	return s
}

func (s *systemPreference) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemPreference) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["status_type"] = s.StatusType
	s.fieldMap["activity_type"] = s.ActivityType
	s.fieldMap["activity_summary"] = s.ActivitySummary
}

func (s systemPreference) clone(db *gorm.DB) systemPreference {
	s.systemPreferenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemPreference) replaceDB(db *gorm.DB) systemPreference {
	s.systemPreferenceDo.ReplaceDB(db)
	return s
}

type systemPreferenceDo struct{ gen.DO }

type ISystemPreferenceDo interface {
	gen.SubQuery
	Debug() ISystemPreferenceDo
	WithContext(ctx context.Context) ISystemPreferenceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemPreferenceDo
	WriteDB() ISystemPreferenceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemPreferenceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemPreferenceDo
	Not(conds ...gen.Condition) ISystemPreferenceDo
	Or(conds ...gen.Condition) ISystemPreferenceDo
	Select(conds ...field.Expr) ISystemPreferenceDo
	Where(conds ...gen.Condition) ISystemPreferenceDo
	Order(conds ...field.Expr) ISystemPreferenceDo
	Distinct(cols ...field.Expr) ISystemPreferenceDo
	Omit(cols ...field.Expr) ISystemPreferenceDo
	Join(table schema.Tabler, on ...field.Expr) ISystemPreferenceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemPreferenceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemPreferenceDo
	Group(cols ...field.Expr) ISystemPreferenceDo
	Having(conds ...gen.Condition) ISystemPreferenceDo
	Limit(limit int) ISystemPreferenceDo
	Offset(offset int) ISystemPreferenceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemPreferenceDo
	Unscoped() ISystemPreferenceDo
	Create(values ...*model.SystemPreference) error
	CreateInBatches(values []*model.SystemPreference, batchSize int) error
	Save(values ...*model.SystemPreference) error
	First() (*model.SystemPreference, error)
	Take() (*model.SystemPreference, error)
	Last() (*model.SystemPreference, error)
	Find() ([]*model.SystemPreference, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemPreference, err error)
	FindInBatches(result *[]*model.SystemPreference, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemPreference) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemPreferenceDo
	Assign(attrs ...field.AssignExpr) ISystemPreferenceDo
	Joins(fields ...field.RelationField) ISystemPreferenceDo
	Preload(fields ...field.RelationField) ISystemPreferenceDo
	FirstOrInit() (*model.SystemPreference, error)
	FirstOrCreate() (*model.SystemPreference, error)
	FindByPage(offset int, limit int) (result []*model.SystemPreference, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemPreferenceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemPreferenceDo) Debug() ISystemPreferenceDo {
	return s.withDO(s.DO.Debug())
}

func (s systemPreferenceDo) WithContext(ctx context.Context) ISystemPreferenceDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemPreferenceDo) ReadDB() ISystemPreferenceDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemPreferenceDo) WriteDB() ISystemPreferenceDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemPreferenceDo) Session(config *gorm.Session) ISystemPreferenceDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemPreferenceDo) Clauses(conds ...clause.Expression) ISystemPreferenceDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemPreferenceDo) Returning(value interface{}, columns ...string) ISystemPreferenceDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemPreferenceDo) Not(conds ...gen.Condition) ISystemPreferenceDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemPreferenceDo) Or(conds ...gen.Condition) ISystemPreferenceDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemPreferenceDo) Select(conds ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemPreferenceDo) Where(conds ...gen.Condition) ISystemPreferenceDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemPreferenceDo) Order(conds ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemPreferenceDo) Distinct(cols ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemPreferenceDo) Omit(cols ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemPreferenceDo) Join(table schema.Tabler, on ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemPreferenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemPreferenceDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemPreferenceDo) Group(cols ...field.Expr) ISystemPreferenceDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemPreferenceDo) Having(conds ...gen.Condition) ISystemPreferenceDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemPreferenceDo) Limit(limit int) ISystemPreferenceDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemPreferenceDo) Offset(offset int) ISystemPreferenceDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemPreferenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemPreferenceDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemPreferenceDo) Unscoped() ISystemPreferenceDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemPreferenceDo) Create(values ...*model.SystemPreference) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemPreferenceDo) CreateInBatches(values []*model.SystemPreference, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemPreferenceDo) Save(values ...*model.SystemPreference) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemPreferenceDo) First() (*model.SystemPreference, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPreference), nil
	}
}

func (s systemPreferenceDo) Take() (*model.SystemPreference, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPreference), nil
	}
}

func (s systemPreferenceDo) Last() (*model.SystemPreference, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPreference), nil
	}
}

func (s systemPreferenceDo) Find() ([]*model.SystemPreference, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemPreference), err
}

func (s systemPreferenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemPreference, err error) {
	buf := make([]*model.SystemPreference, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemPreferenceDo) FindInBatches(result *[]*model.SystemPreference, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemPreferenceDo) Attrs(attrs ...field.AssignExpr) ISystemPreferenceDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemPreferenceDo) Assign(attrs ...field.AssignExpr) ISystemPreferenceDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemPreferenceDo) Joins(fields ...field.RelationField) ISystemPreferenceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemPreferenceDo) Preload(fields ...field.RelationField) ISystemPreferenceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemPreferenceDo) FirstOrInit() (*model.SystemPreference, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPreference), nil
	}
}

func (s systemPreferenceDo) FirstOrCreate() (*model.SystemPreference, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPreference), nil
	}
}

func (s systemPreferenceDo) FindByPage(offset int, limit int) (result []*model.SystemPreference, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemPreferenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemPreferenceDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemPreferenceDo) Delete(models ...*model.SystemPreference) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemPreferenceDo) withDO(do gen.Dao) *systemPreferenceDo {
	s.DO = *do.(*gen.DO)
	return s
}
