// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newTtsMemberPreference(db *gorm.DB, opts ...gen.DOOption) ttsMemberPreference {
	_ttsMemberPreference := ttsMemberPreference{}

	_ttsMemberPreference.ttsMemberPreferenceDo.UseDB(db, opts...)
	_ttsMemberPreference.ttsMemberPreferenceDo.UseModel(&model.TtsMemberPreference{})

	tableName := _ttsMemberPreference.ttsMemberPreferenceDo.TableName()
	_ttsMemberPreference.ALL = field.NewAsterisk(tableName)
	_ttsMemberPreference.UserID = field.NewInt64(tableName, "user_id")
	_ttsMemberPreference.GuildID = field.NewInt64(tableName, "guild_id")
	_ttsMemberPreference.SpeakerID = field.NewInt32(tableName, "speaker_id")
	_ttsMemberPreference.Speed = field.NewInt32(tableName, "speed")

	_ttsMemberPreference.fillFieldMap()

	return _ttsMemberPreference
}

type ttsMemberPreference struct {
	ttsMemberPreferenceDo

	ALL       field.Asterisk
	UserID    field.Int64
	GuildID   field.Int64
	SpeakerID field.Int32
	Speed     field.Int32

	fieldMap map[string]field.Expr
}

func (t ttsMemberPreference) Table(newTableName string) *ttsMemberPreference {
	t.ttsMemberPreferenceDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ttsMemberPreference) As(alias string) *ttsMemberPreference {
	t.ttsMemberPreferenceDo.DO = *(t.ttsMemberPreferenceDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ttsMemberPreference) updateTableName(table string) *ttsMemberPreference {
	t.ALL = field.NewAsterisk(table)
	t.UserID = field.NewInt64(table, "user_id")
	t.GuildID = field.NewInt64(table, "guild_id")
	t.SpeakerID = field.NewInt32(table, "speaker_id")
	t.Speed = field.NewInt32(table, "speed")

	t.fillFieldMap()

	return t
}

func (t *ttsMemberPreference) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ttsMemberPreference) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["guild_id"] = t.GuildID
	t.fieldMap["speaker_id"] = t.SpeakerID
	t.fieldMap["speed"] = t.Speed
}

func (t ttsMemberPreference) clone(db *gorm.DB) ttsMemberPreference {
	t.ttsMemberPreferenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ttsMemberPreference) replaceDB(db *gorm.DB) ttsMemberPreference {
	t.ttsMemberPreferenceDo.ReplaceDB(db)
	return t
}

type ttsMemberPreferenceDo struct{ gen.DO }

type ITtsMemberPreferenceDo interface {
	gen.SubQuery
	Debug() ITtsMemberPreferenceDo
	WithContext(ctx context.Context) ITtsMemberPreferenceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITtsMemberPreferenceDo
	WriteDB() ITtsMemberPreferenceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITtsMemberPreferenceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITtsMemberPreferenceDo
	Not(conds ...gen.Condition) ITtsMemberPreferenceDo
	Or(conds ...gen.Condition) ITtsMemberPreferenceDo
	Select(conds ...field.Expr) ITtsMemberPreferenceDo
	Where(conds ...gen.Condition) ITtsMemberPreferenceDo
	Order(conds ...field.Expr) ITtsMemberPreferenceDo
	Distinct(cols ...field.Expr) ITtsMemberPreferenceDo
	Omit(cols ...field.Expr) ITtsMemberPreferenceDo
	Join(table schema.Tabler, on ...field.Expr) ITtsMemberPreferenceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITtsMemberPreferenceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITtsMemberPreferenceDo
	Group(cols ...field.Expr) ITtsMemberPreferenceDo
	Having(conds ...gen.Condition) ITtsMemberPreferenceDo
	Limit(limit int) ITtsMemberPreferenceDo
	Offset(offset int) ITtsMemberPreferenceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsMemberPreferenceDo
	Unscoped() ITtsMemberPreferenceDo
	Create(values ...*model.TtsMemberPreference) error
	CreateInBatches(values []*model.TtsMemberPreference, batchSize int) error
	Save(values ...*model.TtsMemberPreference) error
	First() (*model.TtsMemberPreference, error)
	Take() (*model.TtsMemberPreference, error)
	Last() (*model.TtsMemberPreference, error)
	Find() ([]*model.TtsMemberPreference, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsMemberPreference, err error)
	FindInBatches(result *[]*model.TtsMemberPreference, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TtsMemberPreference) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITtsMemberPreferenceDo
	Assign(attrs ...field.AssignExpr) ITtsMemberPreferenceDo
	Joins(fields ...field.RelationField) ITtsMemberPreferenceDo
	Preload(fields ...field.RelationField) ITtsMemberPreferenceDo
	FirstOrInit() (*model.TtsMemberPreference, error)
	FirstOrCreate() (*model.TtsMemberPreference, error)
	FindByPage(offset int, limit int) (result []*model.TtsMemberPreference, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITtsMemberPreferenceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ttsMemberPreferenceDo) Debug() ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Debug())
}

func (t ttsMemberPreferenceDo) WithContext(ctx context.Context) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ttsMemberPreferenceDo) ReadDB() ITtsMemberPreferenceDo {
	return t.Clauses(dbresolver.Read)
}

func (t ttsMemberPreferenceDo) WriteDB() ITtsMemberPreferenceDo {
	return t.Clauses(dbresolver.Write)
}

func (t ttsMemberPreferenceDo) Session(config *gorm.Session) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Session(config))
}

func (t ttsMemberPreferenceDo) Clauses(conds ...clause.Expression) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ttsMemberPreferenceDo) Returning(value interface{}, columns ...string) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ttsMemberPreferenceDo) Not(conds ...gen.Condition) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ttsMemberPreferenceDo) Or(conds ...gen.Condition) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ttsMemberPreferenceDo) Select(conds ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ttsMemberPreferenceDo) Where(conds ...gen.Condition) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ttsMemberPreferenceDo) Order(conds ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ttsMemberPreferenceDo) Distinct(cols ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ttsMemberPreferenceDo) Omit(cols ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ttsMemberPreferenceDo) Join(table schema.Tabler, on ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ttsMemberPreferenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ttsMemberPreferenceDo) RightJoin(table schema.Tabler, on ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ttsMemberPreferenceDo) Group(cols ...field.Expr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ttsMemberPreferenceDo) Having(conds ...gen.Condition) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ttsMemberPreferenceDo) Limit(limit int) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ttsMemberPreferenceDo) Offset(offset int) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ttsMemberPreferenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ttsMemberPreferenceDo) Unscoped() ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ttsMemberPreferenceDo) Create(values ...*model.TtsMemberPreference) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ttsMemberPreferenceDo) CreateInBatches(values []*model.TtsMemberPreference, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ttsMemberPreferenceDo) Save(values ...*model.TtsMemberPreference) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ttsMemberPreferenceDo) First() (*model.TtsMemberPreference, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsMemberPreference), nil
	}
}

func (t ttsMemberPreferenceDo) Take() (*model.TtsMemberPreference, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsMemberPreference), nil
	}
}

func (t ttsMemberPreferenceDo) Last() (*model.TtsMemberPreference, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsMemberPreference), nil
	}
}

func (t ttsMemberPreferenceDo) Find() ([]*model.TtsMemberPreference, error) {
	result, err := t.DO.Find()
	return result.([]*model.TtsMemberPreference), err
}

func (t ttsMemberPreferenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsMemberPreference, err error) {
	buf := make([]*model.TtsMemberPreference, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ttsMemberPreferenceDo) FindInBatches(result *[]*model.TtsMemberPreference, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ttsMemberPreferenceDo) Attrs(attrs ...field.AssignExpr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ttsMemberPreferenceDo) Assign(attrs ...field.AssignExpr) ITtsMemberPreferenceDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ttsMemberPreferenceDo) Joins(fields ...field.RelationField) ITtsMemberPreferenceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ttsMemberPreferenceDo) Preload(fields ...field.RelationField) ITtsMemberPreferenceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ttsMemberPreferenceDo) FirstOrInit() (*model.TtsMemberPreference, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsMemberPreference), nil
	}
}

func (t ttsMemberPreferenceDo) FirstOrCreate() (*model.TtsMemberPreference, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsMemberPreference), nil
	}
}

func (t ttsMemberPreferenceDo) FindByPage(offset int, limit int) (result []*model.TtsMemberPreference, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ttsMemberPreferenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ttsMemberPreferenceDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ttsMemberPreferenceDo) Delete(models ...*model.TtsMemberPreference) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ttsMemberPreferenceDo) withDO(do gen.Dao) *ttsMemberPreferenceDo {
	t.DO = *do.(*gen.DO)
	return t
}
