// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newTtsUserPreference(db *gorm.DB, opts ...gen.DOOption) ttsUserPreference {
	_ttsUserPreference := ttsUserPreference{}

	_ttsUserPreference.ttsUserPreferenceDo.UseDB(db, opts...)
	_ttsUserPreference.ttsUserPreferenceDo.UseModel(&model.TtsUserPreference{})

	tableName := _ttsUserPreference.ttsUserPreferenceDo.TableName()
	_ttsUserPreference.ALL = field.NewAsterisk(tableName)
	_ttsUserPreference.UserID = field.NewInt64(tableName, "user_id")
	_ttsUserPreference.SpeakerID = field.NewInt32(tableName, "speaker_id")
	_ttsUserPreference.Speed = field.NewInt32(tableName, "speed")

	_ttsUserPreference.fillFieldMap()

	return _ttsUserPreference
}

type ttsUserPreference struct {
	ttsUserPreferenceDo

	ALL       field.Asterisk
	UserID    field.Int64
	SpeakerID field.Int32
	Speed     field.Int32

	fieldMap map[string]field.Expr
}

func (t ttsUserPreference) Table(newTableName string) *ttsUserPreference {
	t.ttsUserPreferenceDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ttsUserPreference) As(alias string) *ttsUserPreference {
	t.ttsUserPreferenceDo.DO = *(t.ttsUserPreferenceDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ttsUserPreference) updateTableName(table string) *ttsUserPreference {
	t.ALL = field.NewAsterisk(table)
	t.UserID = field.NewInt64(table, "user_id")
	t.SpeakerID = field.NewInt32(table, "speaker_id")
	t.Speed = field.NewInt32(table, "speed")

	t.fillFieldMap()

	return t
}

func (t *ttsUserPreference) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ttsUserPreference) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 3)
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["speaker_id"] = t.SpeakerID
	t.fieldMap["speed"] = t.Speed
}

func (t ttsUserPreference) clone(db *gorm.DB) ttsUserPreference {
	t.ttsUserPreferenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ttsUserPreference) replaceDB(db *gorm.DB) ttsUserPreference {
	t.ttsUserPreferenceDo.ReplaceDB(db)
	return t
}

type ttsUserPreferenceDo struct{ gen.DO }

type ITtsUserPreferenceDo interface {
	gen.SubQuery
	Debug() ITtsUserPreferenceDo
	WithContext(ctx context.Context) ITtsUserPreferenceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITtsUserPreferenceDo
	WriteDB() ITtsUserPreferenceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITtsUserPreferenceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITtsUserPreferenceDo
	Not(conds ...gen.Condition) ITtsUserPreferenceDo
	Or(conds ...gen.Condition) ITtsUserPreferenceDo
	Select(conds ...field.Expr) ITtsUserPreferenceDo
	Where(conds ...gen.Condition) ITtsUserPreferenceDo
	Order(conds ...field.Expr) ITtsUserPreferenceDo
	Distinct(cols ...field.Expr) ITtsUserPreferenceDo
	Omit(cols ...field.Expr) ITtsUserPreferenceDo
	Join(table schema.Tabler, on ...field.Expr) ITtsUserPreferenceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITtsUserPreferenceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITtsUserPreferenceDo
	Group(cols ...field.Expr) ITtsUserPreferenceDo
	Having(conds ...gen.Condition) ITtsUserPreferenceDo
	Limit(limit int) ITtsUserPreferenceDo
	Offset(offset int) ITtsUserPreferenceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsUserPreferenceDo
	Unscoped() ITtsUserPreferenceDo
	Create(values ...*model.TtsUserPreference) error
	CreateInBatches(values []*model.TtsUserPreference, batchSize int) error
	Save(values ...*model.TtsUserPreference) error
	First() (*model.TtsUserPreference, error)
	Take() (*model.TtsUserPreference, error)
	Last() (*model.TtsUserPreference, error)
	Find() ([]*model.TtsUserPreference, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsUserPreference, err error)
	FindInBatches(result *[]*model.TtsUserPreference, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TtsUserPreference) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITtsUserPreferenceDo
	Assign(attrs ...field.AssignExpr) ITtsUserPreferenceDo
	Joins(fields ...field.RelationField) ITtsUserPreferenceDo
	Preload(fields ...field.RelationField) ITtsUserPreferenceDo
	FirstOrInit() (*model.TtsUserPreference, error)
	FirstOrCreate() (*model.TtsUserPreference, error)
	FindByPage(offset int, limit int) (result []*model.TtsUserPreference, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITtsUserPreferenceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ttsUserPreferenceDo) Debug() ITtsUserPreferenceDo {
	return t.withDO(t.DO.Debug())
}

func (t ttsUserPreferenceDo) WithContext(ctx context.Context) ITtsUserPreferenceDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ttsUserPreferenceDo) ReadDB() ITtsUserPreferenceDo {
	return t.Clauses(dbresolver.Read)
}

func (t ttsUserPreferenceDo) WriteDB() ITtsUserPreferenceDo {
	return t.Clauses(dbresolver.Write)
}

func (t ttsUserPreferenceDo) Session(config *gorm.Session) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Session(config))
}

func (t ttsUserPreferenceDo) Clauses(conds ...clause.Expression) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ttsUserPreferenceDo) Returning(value interface{}, columns ...string) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ttsUserPreferenceDo) Not(conds ...gen.Condition) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ttsUserPreferenceDo) Or(conds ...gen.Condition) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ttsUserPreferenceDo) Select(conds ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ttsUserPreferenceDo) Where(conds ...gen.Condition) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ttsUserPreferenceDo) Order(conds ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ttsUserPreferenceDo) Distinct(cols ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ttsUserPreferenceDo) Omit(cols ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ttsUserPreferenceDo) Join(table schema.Tabler, on ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ttsUserPreferenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ttsUserPreferenceDo) RightJoin(table schema.Tabler, on ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ttsUserPreferenceDo) Group(cols ...field.Expr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ttsUserPreferenceDo) Having(conds ...gen.Condition) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ttsUserPreferenceDo) Limit(limit int) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ttsUserPreferenceDo) Offset(offset int) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ttsUserPreferenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ttsUserPreferenceDo) Unscoped() ITtsUserPreferenceDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ttsUserPreferenceDo) Create(values ...*model.TtsUserPreference) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ttsUserPreferenceDo) CreateInBatches(values []*model.TtsUserPreference, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ttsUserPreferenceDo) Save(values ...*model.TtsUserPreference) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ttsUserPreferenceDo) First() (*model.TtsUserPreference, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsUserPreference), nil
	}
}

func (t ttsUserPreferenceDo) Take() (*model.TtsUserPreference, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsUserPreference), nil
	}
}

func (t ttsUserPreferenceDo) Last() (*model.TtsUserPreference, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsUserPreference), nil
	}
}

func (t ttsUserPreferenceDo) Find() ([]*model.TtsUserPreference, error) {
	result, err := t.DO.Find()
	return result.([]*model.TtsUserPreference), err
}

func (t ttsUserPreferenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsUserPreference, err error) {
	buf := make([]*model.TtsUserPreference, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ttsUserPreferenceDo) FindInBatches(result *[]*model.TtsUserPreference, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ttsUserPreferenceDo) Attrs(attrs ...field.AssignExpr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ttsUserPreferenceDo) Assign(attrs ...field.AssignExpr) ITtsUserPreferenceDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ttsUserPreferenceDo) Joins(fields ...field.RelationField) ITtsUserPreferenceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ttsUserPreferenceDo) Preload(fields ...field.RelationField) ITtsUserPreferenceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ttsUserPreferenceDo) FirstOrInit() (*model.TtsUserPreference, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsUserPreference), nil
	}
}

func (t ttsUserPreferenceDo) FirstOrCreate() (*model.TtsUserPreference, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsUserPreference), nil
	}
}

func (t ttsUserPreferenceDo) FindByPage(offset int, limit int) (result []*model.TtsUserPreference, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ttsUserPreferenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ttsUserPreferenceDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ttsUserPreferenceDo) Delete(models ...*model.TtsUserPreference) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ttsUserPreferenceDo) withDO(do gen.Dao) *ttsUserPreferenceDo {
	t.DO = *do.(*gen.DO)
	return t
}
