// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newTtsDictionary(db *gorm.DB, opts ...gen.DOOption) ttsDictionary {
	_ttsDictionary := ttsDictionary{}

	_ttsDictionary.ttsDictionaryDo.UseDB(db, opts...)
	_ttsDictionary.ttsDictionaryDo.UseModel(&model.TtsDictionary{})

	tableName := _ttsDictionary.ttsDictionaryDo.TableName()
	_ttsDictionary.ALL = field.NewAsterisk(tableName)
	_ttsDictionary.UserID = field.NewInt64(tableName, "user_id")
	_ttsDictionary.GuildID = field.NewInt64(tableName, "guild_id")
	_ttsDictionary.Yomi = field.NewString(tableName, "yomi")
	_ttsDictionary.Word = field.NewString(tableName, "word")
	_ttsDictionary.CreatedAt = field.NewTime(tableName, "created_at")

	_ttsDictionary.fillFieldMap()

	return _ttsDictionary
}

type ttsDictionary struct {
	ttsDictionaryDo

	ALL       field.Asterisk
	UserID    field.Int64
	GuildID   field.Int64
	Yomi      field.String
	Word      field.String
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t ttsDictionary) Table(newTableName string) *ttsDictionary {
	t.ttsDictionaryDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ttsDictionary) As(alias string) *ttsDictionary {
	t.ttsDictionaryDo.DO = *(t.ttsDictionaryDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ttsDictionary) updateTableName(table string) *ttsDictionary {
	t.ALL = field.NewAsterisk(table)
	t.UserID = field.NewInt64(table, "user_id")
	t.GuildID = field.NewInt64(table, "guild_id")
	t.Yomi = field.NewString(table, "yomi")
	t.Word = field.NewString(table, "word")
	t.CreatedAt = field.NewTime(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *ttsDictionary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ttsDictionary) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["guild_id"] = t.GuildID
	t.fieldMap["yomi"] = t.Yomi
	t.fieldMap["word"] = t.Word
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t ttsDictionary) clone(db *gorm.DB) ttsDictionary {
	t.ttsDictionaryDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ttsDictionary) replaceDB(db *gorm.DB) ttsDictionary {
	t.ttsDictionaryDo.ReplaceDB(db)
	return t
}

type ttsDictionaryDo struct{ gen.DO }

type ITtsDictionaryDo interface {
	gen.SubQuery
	Debug() ITtsDictionaryDo
	WithContext(ctx context.Context) ITtsDictionaryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITtsDictionaryDo
	WriteDB() ITtsDictionaryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITtsDictionaryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITtsDictionaryDo
	Not(conds ...gen.Condition) ITtsDictionaryDo
	Or(conds ...gen.Condition) ITtsDictionaryDo
	Select(conds ...field.Expr) ITtsDictionaryDo
	Where(conds ...gen.Condition) ITtsDictionaryDo
	Order(conds ...field.Expr) ITtsDictionaryDo
	Distinct(cols ...field.Expr) ITtsDictionaryDo
	Omit(cols ...field.Expr) ITtsDictionaryDo
	Join(table schema.Tabler, on ...field.Expr) ITtsDictionaryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITtsDictionaryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITtsDictionaryDo
	Group(cols ...field.Expr) ITtsDictionaryDo
	Having(conds ...gen.Condition) ITtsDictionaryDo
	Limit(limit int) ITtsDictionaryDo
	Offset(offset int) ITtsDictionaryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsDictionaryDo
	Unscoped() ITtsDictionaryDo
	Create(values ...*model.TtsDictionary) error
	CreateInBatches(values []*model.TtsDictionary, batchSize int) error
	Save(values ...*model.TtsDictionary) error
	First() (*model.TtsDictionary, error)
	Take() (*model.TtsDictionary, error)
	Last() (*model.TtsDictionary, error)
	Find() ([]*model.TtsDictionary, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsDictionary, err error)
	FindInBatches(result *[]*model.TtsDictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TtsDictionary) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITtsDictionaryDo
	Assign(attrs ...field.AssignExpr) ITtsDictionaryDo
	Joins(fields ...field.RelationField) ITtsDictionaryDo
	Preload(fields ...field.RelationField) ITtsDictionaryDo
	FirstOrInit() (*model.TtsDictionary, error)
	FirstOrCreate() (*model.TtsDictionary, error)
	FindByPage(offset int, limit int) (result []*model.TtsDictionary, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITtsDictionaryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ttsDictionaryDo) Debug() ITtsDictionaryDo {
	return t.withDO(t.DO.Debug())
}

func (t ttsDictionaryDo) WithContext(ctx context.Context) ITtsDictionaryDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ttsDictionaryDo) ReadDB() ITtsDictionaryDo {
	return t.Clauses(dbresolver.Read)
}

func (t ttsDictionaryDo) WriteDB() ITtsDictionaryDo {
	return t.Clauses(dbresolver.Write)
}

func (t ttsDictionaryDo) Session(config *gorm.Session) ITtsDictionaryDo {
	return t.withDO(t.DO.Session(config))
}

func (t ttsDictionaryDo) Clauses(conds ...clause.Expression) ITtsDictionaryDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ttsDictionaryDo) Returning(value interface{}, columns ...string) ITtsDictionaryDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ttsDictionaryDo) Not(conds ...gen.Condition) ITtsDictionaryDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ttsDictionaryDo) Or(conds ...gen.Condition) ITtsDictionaryDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ttsDictionaryDo) Select(conds ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ttsDictionaryDo) Where(conds ...gen.Condition) ITtsDictionaryDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ttsDictionaryDo) Order(conds ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ttsDictionaryDo) Distinct(cols ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ttsDictionaryDo) Omit(cols ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ttsDictionaryDo) Join(table schema.Tabler, on ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ttsDictionaryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ttsDictionaryDo) RightJoin(table schema.Tabler, on ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ttsDictionaryDo) Group(cols ...field.Expr) ITtsDictionaryDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ttsDictionaryDo) Having(conds ...gen.Condition) ITtsDictionaryDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ttsDictionaryDo) Limit(limit int) ITtsDictionaryDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ttsDictionaryDo) Offset(offset int) ITtsDictionaryDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ttsDictionaryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsDictionaryDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ttsDictionaryDo) Unscoped() ITtsDictionaryDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ttsDictionaryDo) Create(values ...*model.TtsDictionary) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ttsDictionaryDo) CreateInBatches(values []*model.TtsDictionary, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ttsDictionaryDo) Save(values ...*model.TtsDictionary) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ttsDictionaryDo) First() (*model.TtsDictionary, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsDictionary), nil
	}
}

func (t ttsDictionaryDo) Take() (*model.TtsDictionary, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsDictionary), nil
	}
}

func (t ttsDictionaryDo) Last() (*model.TtsDictionary, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsDictionary), nil
	}
}

func (t ttsDictionaryDo) Find() ([]*model.TtsDictionary, error) {
	result, err := t.DO.Find()
	return result.([]*model.TtsDictionary), err
}

func (t ttsDictionaryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsDictionary, err error) {
	buf := make([]*model.TtsDictionary, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ttsDictionaryDo) FindInBatches(result *[]*model.TtsDictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ttsDictionaryDo) Attrs(attrs ...field.AssignExpr) ITtsDictionaryDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ttsDictionaryDo) Assign(attrs ...field.AssignExpr) ITtsDictionaryDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ttsDictionaryDo) Joins(fields ...field.RelationField) ITtsDictionaryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ttsDictionaryDo) Preload(fields ...field.RelationField) ITtsDictionaryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ttsDictionaryDo) FirstOrInit() (*model.TtsDictionary, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsDictionary), nil
	}
}

func (t ttsDictionaryDo) FirstOrCreate() (*model.TtsDictionary, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsDictionary), nil
	}
}

func (t ttsDictionaryDo) FindByPage(offset int, limit int) (result []*model.TtsDictionary, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ttsDictionaryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ttsDictionaryDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ttsDictionaryDo) Delete(models ...*model.TtsDictionary) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ttsDictionaryDo) withDO(do gen.Dao) *ttsDictionaryDo {
	t.DO = *do.(*gen.DO)
	return t
}
