// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"unibot/internal/model"
)

func newTtsConnection(db *gorm.DB, opts ...gen.DOOption) ttsConnection {
	_ttsConnection := ttsConnection{}

	_ttsConnection.ttsConnectionDo.UseDB(db, opts...)
	_ttsConnection.ttsConnectionDo.UseModel(&model.TtsConnection{})

	tableName := _ttsConnection.ttsConnectionDo.TableName()
	_ttsConnection.ALL = field.NewAsterisk(tableName)
	_ttsConnection.GuildID = field.NewInt64(tableName, "guild_id")
	_ttsConnection.ChannelID = field.NewInt64(tableName, "channel_id")

	_ttsConnection.fillFieldMap()

	return _ttsConnection
}

type ttsConnection struct {
	ttsConnectionDo

	ALL       field.Asterisk
	GuildID   field.Int64
	ChannelID field.Int64

	fieldMap map[string]field.Expr
}

func (t ttsConnection) Table(newTableName string) *ttsConnection {
	t.ttsConnectionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t ttsConnection) As(alias string) *ttsConnection {
	t.ttsConnectionDo.DO = *(t.ttsConnectionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *ttsConnection) updateTableName(table string) *ttsConnection {
	t.ALL = field.NewAsterisk(table)
	t.GuildID = field.NewInt64(table, "guild_id")
	t.ChannelID = field.NewInt64(table, "channel_id")

	t.fillFieldMap()

	return t
}

func (t *ttsConnection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *ttsConnection) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["guild_id"] = t.GuildID
	t.fieldMap["channel_id"] = t.ChannelID
}

func (t ttsConnection) clone(db *gorm.DB) ttsConnection {
	t.ttsConnectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t ttsConnection) replaceDB(db *gorm.DB) ttsConnection {
	t.ttsConnectionDo.ReplaceDB(db)
	return t
}

type ttsConnectionDo struct{ gen.DO }

type ITtsConnectionDo interface {
	gen.SubQuery
	Debug() ITtsConnectionDo
	WithContext(ctx context.Context) ITtsConnectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITtsConnectionDo
	WriteDB() ITtsConnectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITtsConnectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITtsConnectionDo
	Not(conds ...gen.Condition) ITtsConnectionDo
	Or(conds ...gen.Condition) ITtsConnectionDo
	Select(conds ...field.Expr) ITtsConnectionDo
	Where(conds ...gen.Condition) ITtsConnectionDo
	Order(conds ...field.Expr) ITtsConnectionDo
	Distinct(cols ...field.Expr) ITtsConnectionDo
	Omit(cols ...field.Expr) ITtsConnectionDo
	Join(table schema.Tabler, on ...field.Expr) ITtsConnectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITtsConnectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITtsConnectionDo
	Group(cols ...field.Expr) ITtsConnectionDo
	Having(conds ...gen.Condition) ITtsConnectionDo
	Limit(limit int) ITtsConnectionDo
	Offset(offset int) ITtsConnectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsConnectionDo
	Unscoped() ITtsConnectionDo
	Create(values ...*model.TtsConnection) error
	CreateInBatches(values []*model.TtsConnection, batchSize int) error
	Save(values ...*model.TtsConnection) error
	First() (*model.TtsConnection, error)
	Take() (*model.TtsConnection, error)
	Last() (*model.TtsConnection, error)
	Find() ([]*model.TtsConnection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsConnection, err error)
	FindInBatches(result *[]*model.TtsConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TtsConnection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITtsConnectionDo
	Assign(attrs ...field.AssignExpr) ITtsConnectionDo
	Joins(fields ...field.RelationField) ITtsConnectionDo
	Preload(fields ...field.RelationField) ITtsConnectionDo
	FirstOrInit() (*model.TtsConnection, error)
	FirstOrCreate() (*model.TtsConnection, error)
	FindByPage(offset int, limit int) (result []*model.TtsConnection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITtsConnectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t ttsConnectionDo) Debug() ITtsConnectionDo {
	return t.withDO(t.DO.Debug())
}

func (t ttsConnectionDo) WithContext(ctx context.Context) ITtsConnectionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t ttsConnectionDo) ReadDB() ITtsConnectionDo {
	return t.Clauses(dbresolver.Read)
}

func (t ttsConnectionDo) WriteDB() ITtsConnectionDo {
	return t.Clauses(dbresolver.Write)
}

func (t ttsConnectionDo) Session(config *gorm.Session) ITtsConnectionDo {
	return t.withDO(t.DO.Session(config))
}

func (t ttsConnectionDo) Clauses(conds ...clause.Expression) ITtsConnectionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t ttsConnectionDo) Returning(value interface{}, columns ...string) ITtsConnectionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t ttsConnectionDo) Not(conds ...gen.Condition) ITtsConnectionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t ttsConnectionDo) Or(conds ...gen.Condition) ITtsConnectionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t ttsConnectionDo) Select(conds ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t ttsConnectionDo) Where(conds ...gen.Condition) ITtsConnectionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t ttsConnectionDo) Order(conds ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t ttsConnectionDo) Distinct(cols ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t ttsConnectionDo) Omit(cols ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t ttsConnectionDo) Join(table schema.Tabler, on ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t ttsConnectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t ttsConnectionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t ttsConnectionDo) Group(cols ...field.Expr) ITtsConnectionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t ttsConnectionDo) Having(conds ...gen.Condition) ITtsConnectionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t ttsConnectionDo) Limit(limit int) ITtsConnectionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t ttsConnectionDo) Offset(offset int) ITtsConnectionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t ttsConnectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITtsConnectionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t ttsConnectionDo) Unscoped() ITtsConnectionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t ttsConnectionDo) Create(values ...*model.TtsConnection) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t ttsConnectionDo) CreateInBatches(values []*model.TtsConnection, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t ttsConnectionDo) Save(values ...*model.TtsConnection) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t ttsConnectionDo) First() (*model.TtsConnection, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsConnection), nil
	}
}

func (t ttsConnectionDo) Take() (*model.TtsConnection, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsConnection), nil
	}
}

func (t ttsConnectionDo) Last() (*model.TtsConnection, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsConnection), nil
	}
}

func (t ttsConnectionDo) Find() ([]*model.TtsConnection, error) {
	result, err := t.DO.Find()
	return result.([]*model.TtsConnection), err
}

func (t ttsConnectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TtsConnection, err error) {
	buf := make([]*model.TtsConnection, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t ttsConnectionDo) FindInBatches(result *[]*model.TtsConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t ttsConnectionDo) Attrs(attrs ...field.AssignExpr) ITtsConnectionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t ttsConnectionDo) Assign(attrs ...field.AssignExpr) ITtsConnectionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t ttsConnectionDo) Joins(fields ...field.RelationField) ITtsConnectionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t ttsConnectionDo) Preload(fields ...field.RelationField) ITtsConnectionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t ttsConnectionDo) FirstOrInit() (*model.TtsConnection, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsConnection), nil
	}
}

func (t ttsConnectionDo) FirstOrCreate() (*model.TtsConnection, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TtsConnection), nil
	}
}

func (t ttsConnectionDo) FindByPage(offset int, limit int) (result []*model.TtsConnection, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t ttsConnectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t ttsConnectionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t ttsConnectionDo) Delete(models ...*model.TtsConnection) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *ttsConnectionDo) withDO(do gen.Dao) *ttsConnectionDo {
	t.DO = *do.(*gen.DO)
	return t
}
